# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UUWJgVT1_YvNRNIQYh0f7dAb3aakahRk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# Load data
def load_data():
    df = pd.read_csv("https://raw.githubusercontent.com/marceloreis/HTI/master/PRSA_Data_20130301-20170228/PRSA_Data_Shunyi_20130301-20170228.csv")
    return df

df = load_data()


#sidebar
st.sidebar.title("Menu")
option = st.sidebar.radio("Pilih soal:", ["Apa tingkat polutan udara yang paling umum di Shunyi?", "Bagaimana kondisi udara selama waktu periode bulanan dan tahunan?"])


#content
st.title("Dashboard Visualisasi Data Air Quality")

if option == "Apa tingkat polutan udara yang paling umum di Shunyi?":
  polusi = ['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']
  total_polusi = df[polusi].mode().iloc[0]
  st.header("Most Common Air Pollutants")
  plt.figure(figsize=(10, 5))
  total_polusi.plot(kind='bar', color='green')
  plt.title('Most Common Air Pollutants in the Dataset')
  plt.xlabel('Air Pollutant')
  plt.ylabel('Frequency of Occurrence')
  plt.xticks(rotation=50)
  st.pyplot(plt)

else:
  def monthly_air_quality(df):
    return df.groupby('month').agg({'PM2.5': 'mean', 'PM10': 'mean', 'SO2': 'mean', 'NO2': 'mean', 'CO': 'mean', 'O3': 'mean'})
  st.subheader("Monthly Air Quality Visualization")
  monthly_data = monthly_air_quality(df)
  plt.figure(figsize=(10, 5))
  for column in monthly_data.columns:
    plt.plot(monthly_data.index, monthly_data[column], label=column)
  plt.title('Monthly Air Quality')
  plt.xlabel('Month')
  plt.ylabel('Average Value')
  plt.legend()
  st.pyplot(plt)
  def annual_air_quality(df):
    return df.groupby('year').agg({'PM2.5': 'mean', 'PM10': 'mean', 'SO2': 'mean', 'NO2': 'mean', 'CO': 'mean', 'O3': 'mean'})
  st.subheader("Annual Air Quality Visualization")
  annual_data = annual_air_quality(df)
  plt.figure(figsize=(10, 5))
  for column in annual_data.columns:
    plt.plot(annual_data.index, annual_data[column], label=column)
  plt.title('Annual Air Quality')
  plt.xlabel('Year')
  plt.ylabel('Average Value')
  plt.legend()
  st.pyplot(plt)


#conclussion
st.header("Kesimpulan")
st.markdown("""
Trend tingkat polusi udara di Shunyi terdiri dari PM2.5, PM10, SO2, NO2, CO, dan O3. Tingkat polutan udara yang paling umum di Shunyi adalah CO dibandingkan dengan tingkat udara lainnya.

Kondisi udara selama waktu periode bulanan untuk tingkat polusi udara di Shunyi semuanya stabil, kecuali tingkat udara untuk CO yang memiliki peningkatan dan penurunan pada waktu periode bulanan. Kemudian, kondisi udara selama waktu periode tahunan untuk tingkat polusi udara di Shunyi memiliki peningkatan pada tahun 2016-2017.
""")

